name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Flutter action
      uses: subosito/flutter-action@v1.5.3
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Flutter action
      uses: subosito/flutter-action@v1.5.3
    - name: Flutter action1
      run: pub get
    - name: Flutter action1
      run: flutter pub get
    - name: Flutter action1.1
      run: flutter packages pub run build_runner build
    - name: Flutter action2
      run: flutter build apk
